name: accumulate_api
description: JSON RPC Dart client for Accumulate blockchain.
version: 0.2.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  bip39: ^1.0.3
  ed25519_edwards: ^0.3.1
  hex: ^0.2.0
  http: ^0.13.4
  tuple: ^2.0.0
  decimal: ^0.3.5
  json_annotation: ^3.1.1
  dartz: ^0.10.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
