name: accumulate_api6
description: Dart client for Accumulate blockchain, defines basic models and API calls to work with network, supports all types of accounts.
repository: https://github.com/kompendium-ano/accumulate-dart-client
version: 0.3.1

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  crypto: ^3.0.2
  base58check: ^2.0.0
  bitcoin_bip44:
    git:
      url: https://github.com/sigrlami/bitcoin_bip44.git
      ref: master
  bip39: ^1.0.6
  bs58: ^1.0.2
  ed25519_edwards: ^0.3.1
  hex: ^0.2.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  dartz: ^0.10.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  test_html_builder: ^3.0.1
