name: accumulate_api
description: Dart client for Accumulate blockchain, defines basic models and API calls to work with network, supports all types of accounts.
repository: https://github.com/kompendium-ano/accumulate-dart-client
version: 0.3.2

environment:
  sdk: '>=2.13.4 <4.0.0'

dependencies:
  crypto: ^3.0.2
  base58check: ^2.0.0
  bitcoin_bip44_ng: ^0.1.6
  bip39: ^1.0.6
  bs58: ^1.0.2
  ed25519_edwards: ^0.3.1
  hex: ^0.2.0
  http: ^1.1.0
  json_annotation: ^4.4.0
  dartz: ^0.10.0
  collection: ^1.16.0
  csv: ^5.0.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.7