version: 2.1

jobs:
  build:
    working_directory: ~/library
    docker:
      - image: cirrusci/flutter:2.8.1
    steps:
      - checkout:
          path: ~/library

      - run:
          name: Get dependencies
          command: dart pub get

      - run:
          name: Build the library
          command: dart run example/accumulate_example.dart
