version: 2.1

jobs:
  build:
    working_directory: ~/
    docker:
      - image: cirrusci/flutter:2.8.1
    steps:
      - checkout:
          path: ~/

      - run:
          name: Build the library
          command: dart run example/accumulate_example.dart
